services:
  statsfmwidget:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: statsfmwidget
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      DATABASE_URL: file:./prisma/data/dev.db
    ports:
      - "3000:3000"
    volumes:
      - prisma-data:/app/prisma/data
    command: sh -c "npx prisma generate --schema /app/prisma/schema.prisma && npx prisma migrate deploy --schema /app/prisma/schema.prisma && node dist/server.js"

volumes:
  prisma-data:
