services:
  statsfmwidget:
    image: ghcr.io/minerpl/statsfm:latest
    container_name: statsfmwidget
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      DATABASE_URL: file:./data/dev.db
    ports:
      - "3000:3000"
    volumes:
      - prisma-data:/app/prisma/data

volumes:
  prisma-data:
