// Your Application ID goes here. You can find it in your Discord Developer Portal.
const applicationId = "";

// The widget config to import, do not change this unless you know what you're doing.
const widgetData = {"surfaces":{"widget_bottom":{"layout":"widget_bottom_stats","components":{"stat_5":{"fields":{"value":{"value_type":"data","presentation_type":"text","value":"most_streamed_album"},"label":{"value_type":"custom_string","presentation_type":"text","value":"Most Streamed Album"}}},"stat_1":{"fields":{"value":{"value_type":"data","presentation_type":"number","value":"streams"},"label":{"value_type":"custom_string","presentation_type":"text","value":"Total Streams"}}},"stat_3":{"fields":{"value":{"value_type":"data","presentation_type":"number","value":"artists"},"label":{"value_type":"custom_string","presentation_type":"text","value":"Unique Artists"}}},"stat_2":{"fields":{"value":{"value_type":"data","presentation_type":"duration","value":"time"},"label":{"value_type":"custom_string","presentation_type":"text","value":"Streamed Time"}}},"stat_4":{"fields":{"value":{"value_type":"data","presentation_type":"text","value":"most_streamed_artist"},"label":{"value_type":"custom_string","presentation_type":"text","value":"Most Streamed Artist"}}},"stat_6":{"fields":{"value":{"value_type":"data","presentation_type":"text","value":"top_track"},"label":{"value_type":"custom_string","presentation_type":"text","value":"Top Track"}}}}},"add_widget_preview":{"layout":"add_widget_preview_hero","components":{"hero_image":{"fields":{"image":{"value_type":"data","presentation_type":"image","value":"avatar"}}}}},"widget_top":{"layout":"widget_top_hero","components":{"title":{"fields":{"text":{"presentation_type":"text","value_type":"data","value":"username"}}},"subtitle_1":{"fields":{"text":{"value_type":"data","presentation_type":"text","value":"statsfm_username"}}},"hero_image":{"fields":{"image":{"value_type":"data","presentation_type":"image","value":"avatar"}}}}},"mini_profile":{"layout":"mini_profile_hero_stat","components":{"stat":{"fields":{"text":{"value_type":"data","presentation_type":"text","value":"statsfm_username"}}},"hero_image":{"fields":{"image":{"value_type":"data","presentation_type":"image","value":"avatar_small"}}}}},"activity_accessory":{"layout":"activity_accessory_stat","components":{"stat":{"fields":{"text":{"value_type":"data","presentation_type":"text","value":"username"}}}}}}}

// Getting the RestAPI module from Discord's webpack modules so we can send correct request
let wreq= webpackChunkdiscord_developers.push([[Math.random()],{},(r)=>r])
const RestAPI = Object.values(wreq(Object.entries(wreq.m).find(module=>module[1].toString().includes("HTTPUtils"))[0])).find(e=>e?.del)

const config = await RestAPI.post({ url: `/applications/${applicationId}/widget-configs`, body: {display_name: "Stats.FM Widget" }})
const configId = config.body.config_id
await RestAPI.patch({ url: `/applications/${applicationId}/widget-configs/${configId}`, body: widgetData })
await RestAPI.post({ url: `/applications/${applicationId}/widget-configs/${configId}/publish` })
